imm_right_items=set:\u97F3\u4E50\u5531\u7247,\u6536\u85CF,\u8BC4\u8BBA,\u559C\u6B22,\u5206\u4EAB
imm_right_on=false
imm_bottom_bar=false
imm_custom=true
imm_one_click=false
imm_topbar_on=true
imm_collection=false
imm_gold=false
imm_nickname=false
imm_topbar_items=set:\u4FA7\u8FB9\u680F,\u7CBE\u9009,\u540C\u57CE,\u641C\u7D22,\u517B\u8403\u5BA0,\u770B\u6E38\u620F,\u738B\u8005\u9001\u798F\u5229,\u77ED\u5267,\u53D1\u73B0,\u76F4\u64AD,\u5173\u6CE8,\u73A9\u6E38\u620F
flt_ads=true
flt_drama=true
flt_like_on=true
flt_like_th=int:100000
